auto: true
safe: true
server: true
markdown: kramdown
pygments: true
permalink: /:categories/:title
exclude: [stylobate, all.styl, style.styl, style_ie.styl, font_regular.styl]

link_handles:
    - prefix: "@"
      handle: "https://twitter.com/"
    - prefix: "gh:"
      handle: "https://github.com/"

loc:
    fun:
        ru: "Эксперименты"
        en: "Experiments"

        _in_:
            ru: "Экспериментах"
            en: "Experiments"

    issues:
        ru: "Заметки"
        en: "Issues"

        _in_:
            ru: "Заметках"
            en: "Issues"

    old:
        ru: "Старое"
        en: "Old"

        _in_:
            ru: "Старом"
            en: "Old"

    name:
        ru: "Роман Комаров"
        en: "Roman Komarov"
    twitter_name:
        ru: "ki_zu"
        en: "kizmarh"
    twitter_follow:
        ru: "Читайте меня в твиттере"
        en: "Follow me on twitter"
    published:
        ru: "Опубликовано"
        en: "Published on"
    in:
        ru: "в"
        en: "in"
