auto: true
safe: true
server: true
markdown: kramdown
pygments: true
permalink: /:categories/:title
exclude: [stylobate, all.styl, style.styl, style_ie.styl, font_regular.styl]

production_url : http://kizu.ru

github_repo: "kizu/kizu.github.com"

link_handles:
    - prefix: "@"
      handle: "https://twitter.com/"
    - prefix: "gh:"
      handle: "https://github.com/"

# flat_categories:
#    - "fun"
#    - "issues"

prose:
    rooturl: "_posts"
    metadata:
        "_posts": |

            categories: drafts

            layout: post

            invisible: true

        "_posts/fun": |

            categories: fun

            layout: post

        "_posts/issues": |

            categories: issues

            layout: post

        "_posts/blog": |

            categories: blog

            layout: post

        "_posts/en": |

            categories: en drafts

            layout: post

            invisible: true

        "_posts/en/fun": |

            categories: en fun

            layout: post

        "_posts/en/issues": |

            categories: en issues

            layout: post

        "_posts/en/blog": |

            categories: en blog

            layout: post

loc:
    fun:
        ru: "Эксперименты"
        en: "Experiments"

        _in_:
            ru: "Экспериментах"
            en: "Experiments"

    issues:
        ru: "Заметки"
        en: "Issues"

        _in_:
            ru: "Заметках"
            en: "Issues"

    projects:
        ru: "Проекты"
        en: "Projects"

        _in_:
            ru: "Проектах"
            en: "Projects"

    blog:
        ru: "Блог"
        en: "Blog"

        _in_:
            ru: "блоге"
            en: "the Blog"

    old:
        ru: "Старое"
        en: "Old"

        _in_:
            ru: "Старом"
            en: "Old"

    name:
        ru: "Роман Комаров"
        en: "Roman Komarov"
    twitter_name:
        ru: "ki_zu"
        en: "kizmarh"
    twitter_follow:
        ru: "Читайте меня в твиттере"
        en: "Follow me on twitter"
    published:
        ru: "Опубликовано"
        en: "Published on"
    in:
        ru: "в"
        en: "in"
    feedback_text1:
        ru: "Если вы заметили ошибку или хотите чем-то дополнить статью, вы всегда можете или"
        en: "If you've spotted a typo or a mistake, or wish to add something on, you could either"
    feedback_issue:
        ru: "написать мне об этом"
        en: "write me about this"
    feedback_text2:
        ru: "на Гитхабе, или"
        en: "on GitHub, either"
    feedback_edit:
        ru: "отредактировать статью"
        en: "edit this article"
    feedback_text3:
        ru: "с помощью"
        en: "with"
    feedback_for:
        ru: "Отзыв на"
        en: "Feedback for"
    laquo:
        ru: "«"
        en: "“"
    raquo:
        ru: "»"
        en: "”"
